import { PrismaClient } from "../src/generated/prisma";

const prisma = new PrismaClient();

const hmisIndicators = [
  // Section 1: Ante Natal Care (ANC)
  { code: "1.1", name: "Total number of NEW Pregnant Women registered for ANC", description: "Monthly count of new ANC registrations" },
  { code: "1.1.a", name: "Out of total number of NEW Pregnant Women registered with age <15 years", description: "ANC registrations under 15 years" },
  { code: "1.1.b", name: "Out of total number of NEW Pregnant Women registered with age 15-19 years", description: "ANC registrations 15-19 years" },
  { code: "1.1.c", name: "Out of total number of NEW Pregnant Women registered with age >19 to 49 years", description: "ANC registrations 19-49 years" },
  { code: "1.1.d", name: "Out of total number of NEW Pregnant Women registered with age >49 years", description: "ANC registrations over 49 years" },
  { code: "1.1.1", name: "Out of the total NEW ANC registered, number registered within 1st trimester (within 12 weeks)", description: "Early ANC registration rate" },
  { code: "1.1.2", name: "Total ANC footfall/cases (Old cases + New Registration) attended", description: "Total ANC visits" },
  { code: "1.2.1", name: "Number of PW given Td1 (Tetanus Diptheria dose 1)", description: "Td1 vaccination coverage" },
  { code: "1.2.2", name: "Number of PW given Td2 (Tetanus Diptheria dose 2)", description: "Td2 vaccination coverage" },
  { code: "1.2.3", name: "Number of PW given Td Booster (Tetanus Diptheria dose booster)", description: "Td booster coverage" },
  { code: "1.2.4", name: "Number of PW provided full course 180 Iron Folic Acid (IFA) tablets", description: "IFA supplementation coverage" },
  { code: "1.2.5", name: "Number of PW provided full course 360 Calcium tablets", description: "Calcium supplementation coverage" },
  { code: "1.2.6", name: "Number of PW given one Albendazole tablet after 1st trimester", description: "Deworming coverage" },
  { code: "1.2.7", name: "Number of PW received 4 or more ANC check ups", description: "4+ ANC visits coverage" },
  { code: "1.2.8", name: "Number of PW given ANC Corticosteroids in Pre-Term Labour", description: "Corticosteroid administration" },
  { code: "1.3.1", name: "New cases of PW with hypertension detected", description: "Hypertension detection" },
  { code: "1.3.1.a", name: "Number of PW with hypertension managed at institution", description: "Hypertension management" },
  { code: "1.3.2", name: "Number of Eclampsia cases managed during delivery", description: "Eclampsia management" },
  { code: "1.4.1", name: "Number of PW tested for Haemoglobin (Hb) 4 or more than 4 times for respective ANCs", description: "Hb testing frequency" },
  { code: "1.4.2", name: "Number of PW having Hb level<11(7.1 to 10.9 g/dl) (Out of total tested cases)", description: "Mild anemia cases" },
  { code: "1.4.3", name: "Number of PW having Hb level<=7 g/dl (Out of total tested cases)", description: "Severe anemia cases" },
  { code: "1.4.4", name: "Number of PW treated for severe anaemia (Hb<=7g/dl) (Out of total tested cases)", description: "Severe anemia treatment" },
  { code: "1.5.1", name: "Number of PW tested for Blood Sugar using OGTT(Oral Glucose Tolerance Test)", description: "OGTT testing" },
  { code: "1.5.2", name: "Number of PW tested positive for GDM out of total OGTT(Oral Glucose Tolerance Test) conducted", description: "GDM detection" },
  { code: "1.5.3", name: "Number of PW given Insulin out of total tested positive for GDM", description: "Insulin treatment for GDM" },
  { code: "1.5.4", name: "Number of PW given Metformin out of total tested positive for GDM", description: "Metformin treatment for GDM" },
  { code: "1.6.1.a", name: "Number of pregnant/Direct-In-Labor (DIL) women screened/tested (with VDRL/RPR/TPHA/RDT/PoC) for Syphilis", description: "Syphilis screening" },
  { code: "1.6.1.b", name: "Number of pregnant/DIL women found Seropositive for Syphilis by VDRL/RPR/TPHA/RDT/PoC test", description: "Syphilis positive cases" },
  { code: "1.6.1.c", name: "Number of pregnant/DIL women found Syphilis-Seropositive and given treatment with injection Benzathine Penicillin (IM)", description: "Syphilis treatment" },
  { code: "1.6.1.d", name: "Number of live births among Syphilis Seropositive Pregnant Women", description: "Live births from syphilis positive mothers" },
  { code: "1.6.1.e", name: "Number of babies born to Syphilis-Seropositive Pregnant Women tested positive/ clinically diagnosed for congenital Syphilis", description: "Congenital syphilis cases" },
  { code: "1.6.1.f", name: "Out of above, babies with congenital Syphilis received curative treatment", description: "Congenital syphilis treatment" },
  { code: "1.7.1", name: "Number of Pregnant Women tested positive for Thyroid disorder", description: "Thyroid disorder detection" },
  { code: "1.7.2", name: "Number of Pregnant Women treated for thyroid disorder", description: "Thyroid disorder treatment" },
  { code: "1.8.1", name: "Number of Pregnant Women screened for TB", description: "TB screening in pregnancy" },
  { code: "1.8.2", name: "Number of Pregnant Women identified with Presumptive TB symptoms", description: "Presumptive TB in pregnancy" },
  { code: "1.8.3", name: "Number of Pregnant Women referred out of those identified with Presumptive TB symptoms", description: "TB referral in pregnancy" },
  { code: "1.9.1", name: "Total High Risk Pregnancy (HRP) Intrapartum including following", description: "Intrapartum HRP cases" },
  { code: "1.9.1.a", name: "Number of Pregnant Women with Post-Partum Haemorrhage(Immediately after delivery) in the facility", description: "PPH cases" },
  { code: "1.9.1.b", name: "Number of Pregnant Women with Sepsis in the facility", description: "Sepsis cases" },
  { code: "1.9.1.c", name: "Number of Pregnant Women identified with Eclampsia in the facility", description: "Eclampsia cases" },
  { code: "1.9.1.d", name: "Number of Pregnant Women identified with obstructed labour in the facility", description: "Obstructed labour cases" },
  { code: "1.9.2", name: "Total High Risk Pregnancy (HRP) Antepartum (Only New Cases are to be reported)", description: "Antepartum HRP cases" },
  { code: "1.9.3", name: "Total no. of ANC or PNC cases referred to Higher/ any other facility", description: "ANC/PNC referrals out" },
  { code: "1.9.4", name: "Total no. of ANC or PNC cases referred in to the facility", description: "ANC/PNC referrals in" },
  { code: "1.9.5", name: "Number of Complicated pregnancies treated with Blood Transfusion", description: "Blood transfusion in pregnancy" },

  // Section 2: Delivery Care
  { code: "2.1.1.a", name: "Number of Home Deliveries attended by Skill Birth Attendant(SBA) (Doctor/Nurse/ANM)", description: "SBA attended home deliveries" },
  { code: "2.1.1.b", name: "Number of Home Deliveries attended by Non SBA (Trained Birth Attendant(TBA) /Relatives/etc.)", description: "Non-SBA attended home deliveries" },
  { code: "2.1.2", name: "Number of PW given Tablet Misoprostol during home delivery", description: "Misoprostol use in home delivery" },
  { code: "2.1.3", name: "Number of newborns received 7 Home Based Newborn Care (HBNC) visits in case of Home delivery", description: "HBNC visits for home deliveries" },
  { code: "2.2", name: "Number of Institutional Deliveries conducted (Including C-Sections)", description: "Total institutional deliveries" },
  { code: "2.2.1", name: "Out of total institutional deliveries(excluding C-section), number of women stayed for 48 hours or more after delivery", description: "48+ hour stay after delivery" },
  { code: "2.2.2", name: "Out of total Institutional deliveries, number of Institutional Deliveries (Excluding C-Sections) conducted at night (8 PM- 8 AM)", description: "Night deliveries" },
  { code: "2.3", name: "Age wise total number of delivery (Home +Institutional) reported (2.3.1+2.3.2+2.3.3+2.3.4)", description: "Total deliveries by age" },
  { code: "2.3.1", name: "Out of total number of delivery, PW with age <15 years", description: "Deliveries under 15 years" },
  { code: "2.3.2", name: "Out of total number of delivery, PW with age 15-19 years", description: "Deliveries 15-19 years" },
  { code: "2.3.3", name: "Out of total number of delivery, PW with age >19-49 years", description: "Deliveries 19-49 years" },
  { code: "2.3.4", name: "Out of total number of delivery, PW with age > 49 years", description: "Deliveries over 49 years" },
  { code: "2.4", name: "Number of newborns received 6 HBNC visits after Institutional Delivery", description: "HBNC visits after institutional delivery" },
  { code: "2.5", name: "No. of identified Sick new-borns referred by ASHA to facility under HBNC Programme", description: "Sick newborn referrals by ASHA" },
  { code: "2.6", name: "Total number of Children received all scheduled 5 Home visits under HBYC", description: "HBYC home visits" },

  // Section 3: C-Section
  { code: "3.1", name: "Total number of C -Section deliveries performed", description: "Total C-sections" },
  { code: "3.1.1", name: "Out of total C-sections, number performed at night (8 PM- 8 AM)", description: "Night C-sections" },
  { code: "3.1.2", name: "Out of total C-section, number of women stayed for 72 hours or more after delivery", description: "72+ hour stay after C-section" },

  // Section 4: Newborn Care
  { code: "4.1.1.a", name: "Live Birth - Male", description: "Male live births" },
  { code: "4.1.1.b", name: "Live Birth - Female", description: "Female live births" },
  { code: "4.1.2", name: "Number of Pre-term newborns (< 37 weeks of pregnancy)", description: "Preterm births" },
  { code: "4.1.3.a", name: "Intrapartum (Fresh) Still Birth", description: "Fresh stillbirths" },
  { code: "4.1.3.b", name: "Antepartum (Macerated) Still Birth", description: "Macerated stillbirths" },
  { code: "4.2", name: "Abortion (spontaneous)", description: "Spontaneous abortions" },
  { code: "4.3.1.a", name: "Surgical MTPs upto 12 weeks of pregnancy", description: "Surgical MTP up to 12 weeks" },
  { code: "4.3.1.b", name: "MTP more than 12 weeks of pregnancy", description: "MTP after 12 weeks" },
  { code: "4.3.1.c", name: "MTPs completed through Medical methods of abortion (MMA)", description: "Medical MTP" },
  { code: "4.3.2.a", name: "Total Post-abortion/MTP Complications Identified", description: "MTP complications identified" },
  { code: "4.3.2.b", name: "Post-abortion/MTP complications identified (where abortions were carried out in facilities other than public and accredited private health facilities)", description: "MTP complications from other facilities" },
  { code: "4.3.2.c", name: "Post-abortion/MTP Complications treated", description: "MTP complications treated" },
  { code: "4.3.3", name: "Number of women provided with Post-abortion/ MTP contraception", description: "Post-MTP contraception" },
  { code: "4.4.1", name: "Number of Newborns weighed at birth", description: "Newborns weighed at birth" },
  { code: "4.4.2", name: "Number of Newborns having weight less than 2500 gms", description: "Low birth weight babies" },
  { code: "4.4.2.a", name: "Out of the above, number of Newborns having weight less than 1800 gms", description: "Very low birth weight babies" },
  { code: "4.4.3", name: "Number of Newborns breast fed within 1 hour of birth", description: "Early breastfeeding" },
  { code: "4.4.4", name: "No. of Newborns discharged from the facility were exclusively breastfed till discharge", description: "Exclusive breastfeeding till discharge" },
  { code: "4.4.5", name: "Number of Newborns received Donor Human Milk (DHM) in the facility", description: "Donor human milk recipients" },
  { code: "4.5.1", name: "Number of Newborns screened for defects at birth (as per Comprehensive Newborn Screening, RBSK)", description: "Newborn screening" },
  { code: "4.5.1.a", name: "Number of Newborns identified with visible birth defects (including Neural tube defect, Down's Syndrome, Cleft Lip & Palate, Club foot and Developmental dysplasia of the hip)", description: "Birth defects identified" },
  { code: "4.5.3", name: "Number of SNCU discharged babies screened in DEIC", description: "SNCU babies screened in DEIC" },
  { code: "4.5.5", name: "Number of children till age 18 years (affected with selected health conditions) managed for 4 Ds (Disease, Deficiency, Developmental Delay & Defect)", description: "Children managed for 4Ds" },
  { code: "4.5.6", name: "Number of children till age 18 years (affected with selected health conditions) managed by Intervention - Surgical", description: "Children with surgical intervention" },
  { code: "4.5.7", name: "Number of children till age 18 years managed at DEIC (District Early Intervention Centre)", description: "Children managed at DEIC" },

  // Section 5: Nutrition
  { code: "5.1.1", name: "Number of women of reproductive age (WRA) 20-49 years (non-pregnant, non-lactating), provided 4 Red Iron and folic acid (IFA) tablets in a month", description: "WRA IFA supplementation" },
  { code: "5.1.2", name: "Number of children (6-59 months old) provided 8-10 doses (1ml) of IFA syrup (Bi weekly)", description: "Children IFA syrup" },
  { code: "5.1.3.a", name: "Number of out of school children (5 -9 years) given 4-5 IFA Pink tablets at Anganwadi Centres", description: "Out of school children IFA tablets" },
  { code: "5.2.1.c", name: "Number of out of school adolescent girls (10-19 years) having anaemia (Hb 8.1-11.9 g/dl)", description: "Adolescent girls with mild anemia" },
  { code: "5.2.1.e", name: "Number of lactating mothers (of 0-6 months old child) having anaemia (Hb 8.1-11.9 g/dl)", description: "Lactating mothers with mild anemia" },
  { code: "5.2.1.f", name: "Number of women of reproductive age (non-pregnant, non-lactating) (20-49 years) having anaemia (Hb 8.1-11.9 g/dl)", description: "WRA with mild anemia" },
  { code: "5.2.2.c", name: "Number of out of school adolescent girls (10-19 years) having severe anaemia (Hb <8 g/dl)", description: "Adolescent girls with severe anemia" },
  { code: "5.2.2.e", name: "Number of lactating mothers (of 0-6 months old child) having severe anaemia ((Hb <8 g/dl)", description: "Lactating mothers with severe anemia" },
  { code: "5.2.2.f", name: "Number of women of reproductive age (non-pregnant, non-lactating) (20-49 years) having severe anaemia (Hb <8 g/dl)", description: "WRA with severe anemia" },
  { code: "5.2.3.a", name: "Number of anaemic in-school Children (5-9 years) put on treatment", description: "In-school children anemia treatment" },
  { code: "5.2.3.b", name: "Number of anaemic in-school adolescent girls (10-19 years) put on treatment", description: "In-school adolescent girls anemia treatment" },
  { code: "5.2.3.c", name: "Number of anaemic out of school adolescent girls (10-19 years) put on treatment", description: "Out of school adolescent girls anemia treatment" },
  { code: "5.2.3.d", name: "Number of anaemic in-school adolescent boys (10-19 years) put on treatment", description: "In-school adolescent boys anemia treatment" },
  { code: "5.2.3.e", name: "Number of anaemic lactating mothers (of 0-6 months old child) put on treatment", description: "Lactating mothers anemia treatment" },
  { code: "5.2.3.f", name: "Number of anaemic women of reproductive age (non-pregnant, non-lactating) (20-49 years) put on treatment", description: "WRA anemia treatment" },
  { code: "5.2.4.a", name: "Number of lactating mothers (of 0-6 months old child) diagnosed with severe anaemia and put on treatment", description: "Lactating mothers severe anemia treatment" },

  // Section 6: Post Natal Care
  { code: "6.1", name: "In case of home delivery, number of women receiving 1st Postpartum checkups within 48 hours", description: "48-hour PNC for home deliveries" },
  { code: "6.2", name: "Number of women receiving Postpartum checkup between 48 hours and 14 days after Institutional delivery", description: "PNC 48h-14d after institutional delivery" },
  { code: "6.3", name: "Number of mothers provided full course of 180 IFA tablets after delivery", description: "Post-delivery IFA supplementation" },
  { code: "6.4", name: "Number of mothers provided full course 360 Calcium tablets after delivery", description: "Post-delivery calcium supplementation" },

  // Section 7: Family Planning
  { code: "7.1.1", name: "Number of males assessed for STI/RTI", description: "Male STI/RTI assessment" },
  { code: "7.1.1.a", name: "Out of the above, number of males diagnosed with STI/RTI", description: "Male STI/RTI diagnosis" },
  { code: "7.1.1.b", name: "Out of the above, number of males treated for STI/RTI", description: "Male STI/RTI treatment" },
  { code: "7.1.2", name: "Number of females (all females) assessed for STI/RTI", description: "Female STI/RTI assessment" },
  { code: "7.1.2.a", name: "Out of the above, number of females (all females) diagnosed with STI/RTI", description: "Female STI/RTI diagnosis" },
  { code: "7.1.2.b", name: "Out of the above, number of females (all females) treated for STI/RTI", description: "Female STI/RTI treatment" },
  { code: "7.1.3", name: "Number of H/TG assessed for STI/RTI", description: "H/TG STI/RTI assessment" },
  { code: "7.1.3.a", name: "Out of the above, number of H/TG people diagnosed with STI/RTI", description: "H/TG STI/RTI diagnosis" },
  { code: "7.1.3.b", name: "Out of the above, number of H/TG people treated for STI/RTI", description: "H/TG STI/RTI treatment" },

  // Section 8: Family Planning Services
  { code: "8.1.1", name: "Number of Non Scalpel Vasectomy (NSV) / Conventional Vasectomy conducted", description: "Vasectomy procedures" },
  { code: "8.2.1", name: "Number of Laparoscopic sterilizations (excluding post-abortion) conducted", description: "Laparoscopic sterilization" },
  { code: "8.2.2", name: "Number of Interval sterilizations (Mini-lap/Conventional) (other than post-partum and post abortion) conducted", description: "Interval sterilization" },
  { code: "8.2.3", name: "Number of Postpartum sterilizations (within 7 days of delivery by minilap or concurrent with caesarean section) conducted", description: "Postpartum sterilization" },
  { code: "8.2.4", name: "Number of Post-abortion sterilizations (within 7 days of spontaneous or surgical abortion) conducted", description: "Post-abortion sterilization" },
  { code: "8.3", name: "Number of Interval IUCD Insertions (excluding PPIUCD and PAIUCD)", description: "Interval IUCD insertions" },
  { code: "8.4", name: "Number of Postpartum (within 48 hours of delivery) IUCD insertions", description: "Postpartum IUCD insertions" },
  { code: "8.5", name: "Number of Post-abortion (within 12 days of spontaneous or surgical abortion) IUCD insertions", description: "Post-abortion IUCD insertions" },
  { code: "8.6", name: "Number of IUCD Removals", description: "IUCD removals" },
  { code: "8.7", name: "Number of complications following IUCD Insertion", description: "IUCD insertion complications" },
  { code: "8.8", name: "Injectable Contraceptive MPA- First Dose", description: "MPA first dose" },
  { code: "8.9", name: "Injectable Contraceptive MPA- Second Dose", description: "MPA second dose" },
  { code: "8.10", name: "Injectable Contraceptive MPA- Third Dose", description: "MPA third dose" },
  { code: "8.11", name: "Injectable Contraceptive MPA- Fourth and above Dose", description: "MPA fourth and above dose" },
  { code: "8.12", name: "Number of Combined Oral Pill cycles distributed to the beneficiary", description: "Oral pill cycles distributed" },
  { code: "8.13", name: "Number of Condom pieces distributed to the beneficiary", description: "Condom pieces distributed" },
  { code: "8.14", name: "Number of Centchroman (weekly) pill strips distributed to the beneficiary", description: "Centchroman strips distributed" },
  { code: "8.15", name: "Number of Emergency Contraceptive Pills (ECP) given to the beneficiary", description: "ECP distributed" },
  { code: "8.16", name: "Number of Pregnancy Test Kits (PTK) utilized", description: "PTK utilization" },
  { code: "8.17.1", name: "Complications following male sterilization", description: "Male sterilization complications" },
  { code: "8.17.2", name: "Complications following female sterilization", description: "Female sterilization complications" },
  { code: "8.17.3", name: "Failures following male sterilization", description: "Male sterilization failures" },
  { code: "8.17.4", name: "Failures following female sterilization", description: "Female sterilization failures" },
  { code: "8.17.5", name: "Deaths following male sterilization", description: "Male sterilization deaths" },
  { code: "8.17.6", name: "Deaths following female sterilization", description: "Female sterilization deaths" },
  { code: "8.18.1", name: "Number of cases of Female Sterilization followed up (after 1 month or on the resumption of her menstrual cycle whichever is earlier)", description: "Female sterilization follow-up" },
  { code: "8.18.2", name: "Number of cases of Male Sterilization followed up (after 3 months)", description: "Male sterilization follow-up" },

  // Section 9: Immunization
  { code: "9.1.1", name: "Child immunisation - Vitamin K (Birth Dose)", description: "Vitamin K birth dose" },
  { code: "9.1.2", name: "Child immunisation - BCG", description: "BCG vaccination" },
  { code: "9.1.3", name: "Child immunisation - Pentavalent 1", description: "Pentavalent 1" },
  { code: "9.1.4", name: "Child immunisation - Pentavalent 2", description: "Pentavalent 2" },
  { code: "9.1.5", name: "Child immunisation - Pentavalent 3", description: "Pentavalent 3" },
  { code: "9.1.6", name: "Child immunisation - OPV 0 (Birth Dose)", description: "OPV 0 birth dose" },
  { code: "9.1.7", name: "Child immunisation - OPV1", description: "OPV1" },
  { code: "9.1.8", name: "Child immunisation - OPV2", description: "OPV2" },
  { code: "9.1.9", name: "Child immunisation - OPV3", description: "OPV3" },
  { code: "9.1.10", name: "Child immunisation - Hepatitis-B0 (Birth Dose)", description: "Hepatitis B0 birth dose" },
  { code: "9.1.11", name: "Child immunisation - Inactivated Injectable Polio Vaccine 1 (IPV 1)", description: "IPV1" },
  { code: "9.1.12", name: "Child immunisation - Inactivated Injectable Polio Vaccine 2 (IPV 2)", description: "IPV2" },
  { code: "9.1.13", name: "Child immunisation - Rotavirus 1", description: "Rotavirus 1" },
  { code: "9.1.14", name: "Child immunisation - Rotavirus 2", description: "Rotavirus 2" },
  { code: "9.1.15", name: "Child immunisation - Rotavirus 3", description: "Rotavirus 3" },
  { code: "9.1.16", name: "Child immunisation - PCV1", description: "PCV1" },
  { code: "9.1.17", name: "Child immunisation - PCV2", description: "PCV2" },
  { code: "9.2.1", name: "Child immunisation(9 - 11 months) - Inactivated Injectable Polio Vaccine 3 (IPV 3)", description: "IPV3 (9-11 months)" },
  { code: "9.2.2", name: "Child immunisation (9-11months) - Measles & Rubella (MR)/Measles containing vaccine(MCV) - 1st Dose", description: "MR1 (9-11 months)" },
  { code: "9.2.3", name: "Child immunisation (9-11months) - JE 1st dose", description: "JE1 (9-11 months)" },
  { code: "9.2.4", name: "Child immunisation - PCV Booster", description: "PCV Booster" },
  { code: "9.2.5.a", name: "FULLY IMMUNIZED children aged between 9 and <12 months- Male", description: "Fully immunized male children 9-12 months" },
  { code: "9.2.5.b", name: "FULLY IMMUNIZED children aged between 9 and <12 months- Female", description: "Fully immunized female children 9-12 months" },
  { code: "9.3.1", name: "Child immunisation(after 12 months-delayed vaccination) - Measles & Rubella (MR)/Measles containing vaccine(MCV)- 1st Dose", description: "MR1 delayed (after 12 months)" },
  { code: "9.3.2", name: "Child immunisation (after 12 months-delayed vaccination) - JE 1st dose", description: "JE1 delayed (after 12 months)" },
  { code: "9.3.3", name: "Child immunisation - DPT 1 after 12 months of age (delayed vaccination)", description: "DPT1 delayed (after 12 months)" },
  { code: "9.3.4", name: "Child immunisation - DPT 2 after 12 months of age (delayed vaccination)", description: "DPT2 delayed (after 12 months)" },
  { code: "9.3.5", name: "Child immunisation - DPT 3 after 12 months of age (delayed vaccination)", description: "DPT3 delayed (after 12 months)" },
  { code: "9.3.6", name: "Child immunisation - DPT Booster after 24 months of age (delayed vaccination)", description: "DPT Booster delayed (after 24 months)" },
  { code: "9.3.7", name: "Child immunisation - OPV Booster after 24 months of age (delayed vaccination)", description: "OPV Booster delayed (after 24 months)" },
  { code: "9.3.8", name: "Child immunisation - JE Booster after 24 months of age (delayed vaccination)", description: "JE Booster delayed (after 24 months)" },
  { code: "9.4.1", name: "Child immunisation - Measles & Rubella (MR)/ Measles containing vaccine(MCV)- 2nd Dose (16-24 months)", description: "MR2 (16-24 months)" },
  { code: "9.4.2", name: "Child immunisation - DPT 1st Booster", description: "DPT 1st Booster" },
  { code: "9.4.3", name: "Child immunisation - OPV Booster", description: "OPV Booster" },
  { code: "9.4.4", name: "Number of children more than 16 months of age who received Japanese Encephalitis (JE) vaccine- 2nd dose (16-24 months)", description: "JE2 (16-24 months)" },
  { code: "9.5.1", name: "Child Immunization- Typhoid", description: "Typhoid vaccination" },
  { code: "9.5.2", name: "Children more than 5 years received DPT5 (2nd Booster)", description: "DPT5 (2nd Booster) for 5+ years" },
  { code: "9.5.3", name: "Children more than 10 years received Td10 (Tetanus Diptheria10)", description: "Td10 for 10+ years" },
  { code: "9.5.4", name: "Children more than 16 years received Td16 (Tetanus Diptheria16)", description: "Td16 for 16+ years" },
  { code: "9.6.1", name: "Number of cases of AEFI -Minor (eg.- fever, rash, pain etc)", description: "Minor AEFI cases" },
  { code: "9.6.2", name: "Number of cases of AEFI - Severe (eg.- anaphylaxis, fever>102 degrees, not requiring hospitalization etc.)", description: "Severe AEFI cases" },
  { code: "9.6.3", name: "Number of cases of AEFI - Serious (eg.- hospitalization, death, disability , cluster etc.)", description: "Serious AEFI cases" },
  { code: "9.6.3.a", name: "Out of Number of cases of AEFI - Serious , total number of AEFI deaths", description: "AEFI deaths" },
  { code: "9.7.1", name: "Immunisation sessions planned", description: "Planned immunization sessions" },
  { code: "9.7.2", name: "Immunisation sessions held", description: "Held immunization sessions" },
  { code: "9.8.1", name: "Child immunisation - Vitamin A Dose - 1", description: "Vitamin A dose 1" },
  { code: "9.8.2", name: "Child immunisation - Vitamin A Dose - 5", description: "Vitamin A dose 5" },
  { code: "9.8.3", name: "Child immunisation - Vitamin A Dose - 9", description: "Vitamin A dose 9" },

  // Section 10: Childhood Diseases
  { code: "10.1.1", name: "Childhood Diseases - Pneumonia", description: "Childhood pneumonia cases" },
  { code: "10.1.2", name: "Childhood Diseases - Asthma", description: "Childhood asthma cases" },
  { code: "10.1.3", name: "Childhood Diseases - Sepsis", description: "Childhood sepsis cases" },
  { code: "10.1.4", name: "Childhood Diseases - Diphtheria", description: "Childhood diphtheria cases" },
  { code: "10.1.5", name: "Childhood Diseases - Pertussis", description: "Childhood pertussis cases" },
  { code: "10.1.6", name: "Childhood Diseases - Tetanus Neonatorum", description: "Neonatal tetanus cases" },
  { code: "10.1.7", name: "Childhood Diseases - Tuberculosis (TB)", description: "Childhood TB cases" },
  { code: "10.1.8", name: "Childhood Diseases - Acute Flaccid Paralysis(AFP)", description: "AFP cases" },
  { code: "10.1.9", name: "Childhood Diseases - Measles", description: "Childhood measles cases" },
  { code: "10.1.10", name: "Childhood Diseases - Malaria", description: "Childhood malaria cases" },
  { code: "10.1.11", name: "Childhood Diseases - Diarrhoea", description: "Childhood diarrhea cases" },
  { code: "10.1.12", name: "Childhood Diseases - Diarrhoea treated with ORS", description: "Diarrhea treated with ORS" },
  { code: "10.1.13", name: "Childhood Diseases - Diarrhoea treated with Zinc for 14 days", description: "Diarrhea treated with Zinc" },
  { code: "10.1.14", name: "Childhood Diseases -Leprosy Cases", description: "Childhood leprosy cases" },
  { code: "10.1.15", name: "Childhood Diseases- Leprosy with Grade II disability", description: "Childhood leprosy with Grade II disability" },
  { code: "10.2.1", name: "Children admitted with Respiratory Infections", description: "Children admitted with respiratory infections" },
  { code: "10.2.2", name: "Children admitted with Pneumonia", description: "Children admitted with pneumonia" },
  { code: "10.2.3", name: "Children admitted with Diarrhoea", description: "Children admitted with diarrhea" },

  // Section 11: Vector Borne Diseases
  { code: "11.1.1.a", name: "Total Blood Smears Examined for Malaria", description: "Blood smears examined for malaria" },
  { code: "11.1.1.b", name: "Malaria (Microscopy Tests ) - Plasmodium Vivax test positive", description: "P. vivax positive cases" },
  { code: "11.1.1.c", name: "Malaria (Microscopy Tests ) - Plasmodium Falciparum test positive", description: "P. falciparum positive cases" },
  { code: "11.1.1.d", name: "Malaria (Microscopy Tests ) - Mixed test positive", description: "Mixed malaria positive cases" },
  { code: "11.1.2.a", name: "RDT conducted for Malaria", description: "Malaria RDT conducted" },
  { code: "11.1.2.b", name: "Malaria (RDT) - Plasmodium Vivax test positive", description: "RDT P. vivax positive" },
  { code: "11.1.2.c", name: "Malaria (RDT) - Plasmodium Falciparum test positive", description: "RDT P. falciparum positive" },
  { code: "11.1.2.d", name: "Malaria (RDT) - Mixed test positive", description: "RDT mixed malaria positive" },
  { code: "11.2.1", name: "Kala Azar (RDT) - Tests Conducted", description: "Kala azar RDT tests" },
  { code: "11.2.2", name: "Kala Azar Positive Cases", description: "Kala azar positive cases" },
  { code: "11.3.1", name: "Dengue - Enzyme- Linked Immuno Sorbent Assay (ELISA) test conducted", description: "Dengue ELISA tests" },
  { code: "11.3.2", name: "Dengue - Enzyme- Linked Immuno Sorbent Assay (ELISA) test found positive", description: "Dengue ELISA positive" },
  { code: "11.3.3", name: "Chikungunya Enzyme- Linked Immuno Sorbent Assay (ELISA) test conducted", description: "Chikungunya ELISA tests" },
  { code: "11.3.4", name: "Chikungunya Enzyme- Linked Immuno Sorbent Assay (ELISA) test found positive", description: "Chikungunya ELISA positive" },
  { code: "11.4.1", name: "No. of AES cases tested for JE(IgM ELISA)", description: "AES cases tested for JE" },
  { code: "11.4.2", name: "No. of JE positive cases", description: "JE positive cases" },
  { code: "11.5.1", name: "Number of persons that consumed MDA(Mass Drug Administration) drugs during the MDA round", description: "MDA drug consumption" },
  { code: "11.5.2", name: "Number of Lymphatic Filarisis lymphoedema patients received MMDP(Morbidity Management And Disability Prevention) kits", description: "Lymphoedema patients with MMDP kits" },
  { code: "11.5.3", name: "Number of Hydrocele surgeries conducted in Lymphatic Filariasis (MMDP)", description: "Hydrocele surgeries in LF" },

  // Section 12: Adolescent Health
  { code: "12.1.1.a", name: "Girls registered in AFHC", description: "Girls registered in AFHC" },
  { code: "12.1.1.b", name: "Boys registered in AFHC", description: "Boys registered in 