import { PrismaClient } from "../src/generated/prisma";

const prisma = new PrismaClient();

// List of Sub-Center fields with their specified type ("BINARY" for Yes/No, "CONSTANT" for Blank)
const SUBCENTER_FIELDS = [
	{ name: "Total OPD Footfall (M&F) as per HWC portal", type: "CONSTANT" },
	{ name: "Total Catchment population including (Clinics)", type: "CONSTANT" },
	{ name: "Total Wellness Sessions (Awareness/Yoga/Fitness etc.) conducted", type: "CONSTANT" },
	{ name: "Whether Monthly Service Delivery report have been submitted before 5th of the month in AAM Portal", type: "BINARY" },
	{ name: "Are there any new pregnant women in the month", type: "BINARY" },
	{ name: "Whether new pregnant women registered for ANC reported in HMIS is reported in RCH 2.0?", type: "BINARY" },
	{ name: "Whether Total pregnant women registered within 1st Trimester reported in HMIS is updated in RCH 2.0", type: "BINARY" },
	{ name: "No of Sputum sample collected and sent for TB testing at NAAT center", type: "CONSTANT" },
	{ name: "No of TB presumptive identified", type: "CONSTANT" },
	{ name: "Are there any pregnant women in the catchment area", type: "BINARY" },
	{ name: "Total Pregnant Women provided 180 IFA (full course) tablets", type: "CONSTANT" },
	{ name: "Total PW due for ANC", type: "CONSTANT" },
	{ name: "Total No of PW received 4 or more ANC check up reported in HMIS", type: "CONSTANT" },
	{ name: "Total PW in the catchment area", type: "CONSTANT" },
	{ name: "No of CBAC form filled in the month", type: "CONSTANT" },
	{ name: "Total of.FP commodities(any) indent/issues generated by facility", type: "CONSTANT" },
	{ name: "Individuals screened for TB at OPD/Outreach/Shivir using Cough App", type: "CONSTANT" },
	{ name: "Are there any new Pulmonary TB diagnosed", type: "BINARY" },
	{ name: "Household visited for TB contact tracing for newly Notified Pulm TB", type: "CONSTANT" },
	{ name: "Are there any patients(any type) currently undergoing treatment?", type: "BINARY" },
	{ name: "No. of TB patients under treatment conducted follow up for Differentiated TB Care", type: "CONSTANT" },
	{ name: "RI sessions planned(including clinics)", type: "CONSTANT" },
	{ name: "No of RI sessions held(including clinics)", type: "CONSTANT" },
	{ name: "Total beneficiary for RI (due list)", type: "CONSTANT" },
	{ name: "Total RI footfall", type: "CONSTANT" },
	{ name: "HTN screened (including rescreened) for the month", type: "CONSTANT" },
	{ name: "Total 30+ population in the catchment area", type: "CONSTANT" },
	{ name: "DM screened (including rescreened) for the month", type: "CONSTANT" },
	{ name: "Same as Q.20 (30+Population)", type: "CONSTANT" },
	{ name: "Oral Ca. Screened for the month", type: "CONSTANT" },
	{ name: "Same as Q.20 (30+Population) - Oral Ca", type: "CONSTANT" },
	{ name: "Breast & Cervical Ca. screened for the month", type: "CONSTANT" },
	{ name: "Total 30+ Female population", type: "CONSTANT" },
	{ name: "No of HTN diagnosed", type: "CONSTANT" },
	{ name: "No of HTN sreened & referred to higher facility", type: "CONSTANT" },
	{ name: "No of DM diagnosed", type: "CONSTANT" },
	{ name: "No of DM sreened & referred to higher facility", type: "CONSTANT" },
	{ name: "No of HTN clients follow up", type: "CONSTANT" },
	{ name: "No of HTN clients under treatment", type: "CONSTANT" },
	{ name: "No of DM clients follow up", type: "CONSTANT" },
	{ name: "No of DM clients under treatment", type: "CONSTANT" },
	{ name: "Patient satisfaction score for the month", type: "CONSTANT" },
	{ name: "No of patients identified for Elderly/Palliative home visit", type: "CONSTANT" },
	{ name: "No of Elderly & Palliative patients visited", type: "CONSTANT" },
	{ name: "No of Elderly clinic conducted in a month", type: "CONSTANT" },
	{ name: "HWO undergone National NQAS assessment (Virtual/Physical)", type: "BINARY" },
	{ name: "No. of issues generated in DVDMS", type: "CONSTANT" },
	{ name: "No of case reported in S-form (IDSP-IHIP) for the month", type: "CONSTANT" },
] as const;

function generateCode(name: string, index: number): string {
	const slug = name
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "_")
		.replace(/^_+|_+$/g, "")
		.substring(0, 40);
	return `sc_${slug}_${index + 1}`;
}

async function setupSubcenterFields() {
	const isDryRun = process.argv.includes("--dry-run") || process.env.DRY_RUN === "true";

	if (isDryRun) {
		console.log("🔍 RUNNING IN DRY-RUN MODE: No changes will be written to the database.\n");
	} else {
		console.log("🚀 Starting Sub-Center field creation and mapping script...\n");
	}

	try {
		// 1. Find Sub-Center Facility Type (SC_HWC or Sub Centre)
		const subCenterFacilityType = await prisma.facility_type.findFirst({
			where: {
				OR: [
					{ name: "SC_HWC" },
					{ name: { contains: "SC", mode: "insensitive" } },
					{ display_name: { contains: "Sub Centre", mode: "insensitive" } },
				],
			},
		});

		if (!subCenterFacilityType) {
			throw new Error("❌ Sub Centre facility type (SC_HWC) not found in database!");
		}

		console.log(`📍 Found Sub Centre Facility Type: ${subCenterFacilityType.display_name} (${subCenterFacilityType.name}, ID: ${subCenterFacilityType.id})`);

		// 2. Existing mappings count
		const existingMappingsCount = await prisma.facility_field_mapping.count({
			where: { facility_type_id: subCenterFacilityType.id },
		});

		if (isDryRun) {
			console.log(`🧹 [DRY-RUN] Would clear ${existingMappingsCount} existing field mappings for Sub Centre facility.`);
		} else {
			const deletedMappings = await prisma.facility_field_mapping.deleteMany({
				where: { facility_type_id: subCenterFacilityType.id },
			});
			console.log(`🧹 Cleared ${deletedMappings.count} existing field mappings for Sub Centre facility.`);
		}

		// 3. Process fields
		let createdCount = 0;
		let updatedCount = 0;
		let mappedCount = 0;

		for (let i = 0; i < SUBCENTER_FIELDS.length; i++) {
			const item = SUBCENTER_FIELDS[i];
			const code = generateCode(item.name, i);
			const sortOrder = i + 1;

			// Check if field with this code or name already exists
			let fieldObj = await prisma.field.findFirst({
				where: {
					OR: [{ code }, { name: item.name }],
				},
			});

			if (!fieldObj) {
				createdCount++;
				if (isDryRun) {
					console.log(`  ✨ [DRY-RUN ${sortOrder}/48] Would CREATE field: "${item.name}" (${code}) [${item.type}]`);
				} else {
					fieldObj = await prisma.field.create({
						data: {
							code,
							name: item.name,
							field_type: item.type as "BINARY" | "CONSTANT",
							user_type: "ADMIN",
							field_category: "DATA_FIELD",
							is_active: true,
							default_value: null,
							sort_order: sortOrder,
							updated_at: new Date(),
						},
					});
					console.log(`  ✨ [${sortOrder}/48] Created field: "${item.name}" (${fieldObj.code}) [${item.type}]`);
				}
			} else {
				updatedCount++;
				if (isDryRun) {
					console.log(`  🔄 [DRY-RUN ${sortOrder}/48] Would UPDATE field ID ${fieldObj.id}: "${item.name}" (${fieldObj.code}) [${item.type}]`);
				} else {
					fieldObj = await prisma.field.update({
						where: { id: fieldObj.id },
						data: {
							field_type: item.type as "BINARY" | "CONSTANT",
							user_type: "ADMIN",
							field_category: "DATA_FIELD",
							is_active: true,
							default_value: null,
							sort_order: sortOrder,
							updated_at: new Date(),
						},
					});
					console.log(`  🔄 [${sortOrder}/48] Updated field: "${item.name}" (${fieldObj.code}) [${item.type}]`);
				}
			}

			mappedCount++;
			if (isDryRun) {
				console.log(`     🔗 [DRY-RUN] Would MAP field to Sub Centre (display_order: ${sortOrder})`);
			} else if (fieldObj) {
				// Find matching indicator group by code or name
				const groupMatch = await prisma.indicator_group.findFirst({
					where: {
						OR: [
							{ code: { contains: fieldObj.code, mode: "insensitive" } },
							{ name: { contains: fieldObj.name, mode: "insensitive" } },
						],
					},
				});

				await prisma.facility_field_mapping.create({
					data: {
						facility_type_id: subCenterFacilityType.id,
						field_id: fieldObj.id,
						group_id: groupMatch?.id ?? null,
						display_order: sortOrder,
						is_required: false,
						updated_at: new Date(),
					},
				});
			}
		}

		if (isDryRun) {
			console.log(`\n🔍 DRY-RUN COMPLETE: Analyzed ${SUBCENTER_FIELDS.length} fields. (${createdCount} would be created, ${updatedCount} would be updated, ${mappedCount} would be mapped). NO DB CHANGES WERE MADE.`);
		} else {
			console.log(`\n🎉 Success! Processed ${SUBCENTER_FIELDS.length} fields (${createdCount} new created, ${mappedCount} mapped to Sub Centre).`);
		}
	} catch (e) {
		console.error("❌ Error in Sub-Center fields setup script:", e);
	} finally {
		await prisma.$disconnect();
	}
}

setupSubcenterFields();
